[tox]
envlist = py312,flake8,mypy

[testenv]
deps = -rrequirements.txt
commands = pytest tests

[testenv:flake8]
basepython = python3.12
skip_install = true
deps = flake8
commands = flake8 --max-line-length=120 --exclude="./venv/,./.venv/,./.tox/,./build/,./dist/" .

[testenv:mypy]
basepython = python3.12
skip_install = true
deps =
    mypy
    ../whitakers_words
commands = mypy elisio

[pytest]
python_files = Test_*.py test_*.py
