# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:37
from __future__ import unicode_literals
from django.db import migrations
import os
import enumfields.fields
import Elisio.engine.VerseFactory

def load_initial_data(self, orm):
    try:
        os.remove('Elisio/fixtures/verses/initial_data.xml')
    except OSError:
        pass
    if not os.path.exists('Elisio/fixtures/verses/'):
        os.makedirs('Elisio/fixtures/verses/')
    from django.core.management import call_command
    call_command('loaddata', 'initial_data.xml')

class Migration(migrations.Migration):

    dependencies = [
        ('Elisio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseverse',
            name='verseType',
            field=enumfields.fields.EnumField(default=1, enum=Elisio.engine.VerseFactory.VerseType, max_length=10),
        ),
        migrations.AddField(
            model_name='poem',
            name='verseForm',
            field=enumfields.fields.EnumField(default=1, enum=Elisio.engine.VerseFactory.VerseForm, max_length=10),
        ),
        migrations.RunPython(load_initial_data)
    ]
