# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:37
from __future__ import unicode_literals

from django.db import migrations

def load_initial_data(self, orm):
    from Elisio.batchjob import fill_xml_object
    #fill_xml_object()
    from django.core.management import call_command
    #call_command('loaddata', 'initial_data.xml')

class Migration(migrations.Migration):

    dependencies = [
        ('Elisio', '0001_initial'),
        ('Elisio', '0002_auto_20160501_1137'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
