# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:29
import elisio.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elisio', '0006_auto_20170619_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='dependent_on',
        ),
        migrations.RemoveField(
            model_name='databasebatchitem',
            name='negation',
        ),
        migrations.AddField(
            model_name='databasebatchitem',
            name='dependent_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='elisio.DatabaseBatchItem'),
        ),
        migrations.AlterField(
            model_name='databasebatchitem',
            name='object_type',
            field=enumfields.fields.EnumField(enum=elisio.models.scan.ObjectType, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='databasebatchitem',
            name='relation',
            field=enumfields.fields.EnumField(enum=elisio.models.scan.RelationType, max_length=10, null=True),
        ),
    ]
