# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elisio', '0007_auto_20170625_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='opus',
            options={'verbose_name_plural': 'opera'},
        ),
    ]
