# Generated by Django 3.1.7 on 2021-04-01 20:28

from django.db import migrations, models
import elisio.util.utils


class Migration(migrations.Migration):

    dependencies = [
        ('elisio', '0008_auto_20171003_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='commit',
            field=models.CharField(default=elisio.util.utils.get_commit, max_length=80),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='initiator',
            field=models.CharField(default='', max_length=80),
        ),
    ]
